import { EMBEDDING_MODEL, LLM_MODEL } from './model';
import { SECURITY_SOPS } from './sops';
import type { HttpLogRow, LlmToolOutput, SocEnv } from './types';

const META_SOPS_SEEDED = 'internal:vectorize_sops_seeded';

export function tryParseJsonMessage(message: string | ArrayBuffer): unknown | null {
  try {
    if (typeof message === 'string') return JSON.parse(message);
    return JSON.parse(new TextDecoder().decode(message));
  } catch {
    return null;
  }
}

function escapeWafLiteral(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

export function buildSystemPrompt(sopContext: string): string {
  return [
    '# Role: Autonomous Edge Security Analyst (AESA)',
    'You are a senior SOC Engineer at Cloudflare. Your goal is to investigate, analyze, and neutralize web-borne threats in real-time.',
    '',
    '# Retrieved procedures (RAG):',
    sopContext || '(none)',
    '',
    '# Environment:',
    '- `check_logs` queries a real D1 database of edge HTTP request logs. Output parameters that narrow the search.',
    '- `generate_waf_rule` produces a Cloudflare WAF Custom Rule JSON (use evidence from prior log rows when possible).',
    '- `ask_user` asks a clarifying question.',
    '',
    '# check_logs parameters (use JSON fields inside parameters):',
    '- `timeframe`: one of `last_10_mins`, `last_hour`, `last_24h`.',
    '- `suspicious_keyword`: substring to match in signature, path, or body snippet (e.g. UNION, script, etc.).',
    '- Optional `asn` if you already know the source ASN.',
    '',
    '# Investigative SOP:',
    '1. Triage the symptom.',
    '2. If you need evidence, call `check_logs` with a useful timeframe + keyword.',
    '3. After you have log evidence, call `generate_waf_rule` with `asn` and `payload` matching the worst offending traffic.',
    '',
    '# Guidelines:',
    '- You MUST ONLY output valid JSON (no markdown, no extra text).',
    '- Your output MUST match this exact JSON shape:',
    '  {',
    '    "action": "check_logs" | "generate_waf_rule" | "ask_user",',
    '    "reasoning": "...",',
    '    "parameters": { ... }',
    '  }',
  ].join('\n');
}

export function buildUserPrompt(
  symptom: string,
  includeLogs: boolean,
  logText: string | null,
): string {
  return [
    `Symptom reported by user:\n${symptom}`,
    '',
    'Investigation goal:',
    '- Identify attack patterns (SQLi, XSS, DDoS, credential stuffing, etc.).',
    '- Use log evidence when available to choose ASN and payload for mitigation.',
    '',
    includeLogs && logText
      ? `Evidence (D1 log query results):\n${logText}`
      : 'Evidence (D1 logs): not provided yet — call check_logs if needed.',
    '',
    'Decide the next action and respond using the required JSON shape.',
  ].join('\n');
}

export function buildWafRuleFromParameters(
  parameters: Record<string, unknown>,
  evidence?: { topAsn?: number; topPayload?: string; topIp?: string },
): Record<string, unknown> {
  const fromParamsAsn =
    typeof parameters.asn === 'number'
      ? parameters.asn
      : typeof parameters.asn === 'string' && parameters.asn.trim().length > 0
        ? Number(parameters.asn)
        : undefined;

  const fromParamsPayload =
    typeof parameters.payload === 'string' && parameters.payload.trim().length > 0
      ? parameters.payload
      : undefined;

  const asn = fromParamsAsn ?? evidence?.topAsn;
  const payload = fromParamsPayload ?? evidence?.topPayload;

  if (asn === undefined || Number.isNaN(asn)) {
    throw new Error('WAF rule requires a valid ASN from parameters or log evidence.');
  }
  if (!payload || payload.trim().length === 0) {
    throw new Error('WAF rule requires a payload/signature from parameters or log evidence.');
  }

  const lcPayload = escapeWafLiteral(payload.toLowerCase());

  return {
    kind: 'cloudflare_waf_rule',
    action: 'block',
    description: 'Auto-generated by Autonomous Edge Security Agent',
    expression: `ip.src.asnum eq ${asn} and (contains(tolower(http.request.body), "${lcPayload}") or contains(tolower(http.request.uri), "${lcPayload}"))`,
    target: {
      asn,
      payload,
      ...(evidence?.topIp ? { ip: evidence.topIp } : {}),
    },
  };
}

export async function queryLlmNextAction(
  env: SocEnv,
  symptom: string,
  includeLogs: boolean,
  logText: string | null,
  sopContext: string,
): Promise<LlmToolOutput> {
  const systemPrompt = buildSystemPrompt(sopContext);
  const userPrompt = buildUserPrompt(symptom, includeLogs, logText);

  let result: unknown;
  let lastError: Error | null = null;
  const maxRetries = 3;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      result = await env.AI.run(LLM_MODEL as any, {
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt },
        ],
        temperature: 0.2,
        max_tokens: 768,
      });
      lastError = null;
      break;
    } catch (err) {
      lastError = err instanceof Error ? err : new Error(String(err));
      console.warn(`AI attempt ${attempt} failed: ${lastError.message}`);
      if (attempt < maxRetries) {
        await new Promise((r) => setTimeout(r, 500 * attempt));
      }
    }
  }

  if (lastError) {
    throw new Error(`Inference persistently failed after ${maxRetries} attempts: ${lastError.message}`);
  }

  const raw =
    typeof result === 'string'
      ? result
      : typeof (result as { response?: string })?.response === 'string'
        ? (result as { response: string }).response
        : (result as { response?: unknown })?.response ?? result;

  const maybeParsed =
    typeof raw === 'string' && raw.length > 0 ? tryParseJsonMessage(raw) : raw;

  if (!maybeParsed || typeof maybeParsed !== 'object') {
    throw new Error('LLM response was not valid JSON or object.');
  }

  const parsed = maybeParsed as Record<string, unknown>;
  const action = parsed.action;
  const reasoning = parsed.reasoning;
  const parameters = parsed.parameters;

  if (
    (action !== 'check_logs' && action !== 'generate_waf_rule' && action !== 'ask_user') ||
    typeof reasoning !== 'string' ||
    typeof parameters !== 'object' ||
    parameters === null
  ) {
    throw new Error('LLM JSON did not match required schema.');
  }

  return {
    action,
    reasoning,
    parameters: parameters as LlmToolOutput['parameters'],
  };
}

function timeframeSqlClause(timeframe: string | undefined): string {
  switch (timeframe) {
    case 'last_10_mins':
      return `ts >= datetime('now', '-10 minutes')`;
    case 'last_hour':
      return `ts >= datetime('now', '-1 hour')`;
    case 'last_24h':
      return `ts >= datetime('now', '-24 hours')`;
    default:
      return `ts >= datetime('now', '-1 hour')`;
  }
}

export async function queryHttpLogsFromD1(
  db: D1Database,
  parameters: LlmToolOutput['parameters'],
): Promise<{ rows: HttpLogRow[]; summary: Record<string, unknown> }> {
  const timeframe = typeof parameters.timeframe === 'string' ? parameters.timeframe : undefined;
  const kw =
    (typeof parameters.suspicious_keyword === 'string' && parameters.suspicious_keyword.trim().length > 0
      ? parameters.suspicious_keyword
      : typeof parameters.payload === 'string' && parameters.payload.trim().length > 0
        ? parameters.payload
        : '') || '';

  const tClause = timeframeSqlClause(timeframe);
  const binds: string[] = [];

  let sql = `
    SELECT ts, src_asn, src_ip, threat_type, signature, request_path, request_body_snippet, is_malicious
    FROM http_logs
    WHERE ${tClause}
  `;

  if (kw.length > 0) {
    const like = `%${kw}%`;
    sql += ` AND (signature LIKE ? OR request_body_snippet LIKE ? OR request_path LIKE ?)`;
    binds.push(like, like, like);
  }

  if (typeof parameters.asn === 'number' && !Number.isNaN(parameters.asn)) {
    sql += ` AND src_asn = ?`;
    binds.push(String(parameters.asn));
  }

  sql += ` ORDER BY ts DESC LIMIT 80`;

  const stmt = db.prepare(sql);
  const res = await stmt.bind(...binds).all<HttpLogRow>();

  const rows = res.results ?? [];
  const malicious = rows.filter((r) => r.is_malicious === 1);
  const asnCounts = new Map<number, number>();
  for (const r of malicious.length ? malicious : rows) {
    asnCounts.set(r.src_asn, (asnCounts.get(r.src_asn) ?? 0) + 1);
  }
  let topAsn = rows[0]?.src_asn;
  if (topAsn !== undefined) {
    for (const [asn, c] of asnCounts) {
      if (c > (asnCounts.get(topAsn!) ?? 0)) topAsn = asn;
    }
  }

  const summary = {
    rowCount: rows.length,
    maliciousCount: malicious.length,
    topAsn: topAsn ?? null,
    keyword: kw || null,
    timeframe: timeframe ?? 'default',
  };

  return { rows, summary };
}

export function formatLogRowsForLlm(rows: HttpLogRow[]): string {
  const sample = rows.slice(0, 40);
  return JSON.stringify(
    {
      note: 'Rows from D1 (real query).',
      sample,
    },
    null,
    2,
  );
}

export function summarizeEvidenceForWaf(rows: HttpLogRow[]): {
  topAsn?: number;
  topPayload?: string;
  topIp?: string;
} {
  if (!rows.length) return {};
  const malicious = rows.filter((r) => r.is_malicious === 1);
  const pool = malicious.length ? malicious : rows;
  const asnCounts = new Map<number, number>();
  for (const r of pool) {
    asnCounts.set(r.src_asn, (asnCounts.get(r.src_asn) ?? 0) + 1);
  }
  let topAsn = pool[0].src_asn;
  for (const [asn, c] of asnCounts) {
    if (c > (asnCounts.get(topAsn) ?? 0)) topAsn = asn;
  }
  const sigRow = pool.find((r) => r.signature && r.signature.length > 0);
  const topPayload = sigRow?.signature ?? undefined;
  const asnRow = pool.find((r) => r.src_asn === topAsn);
  return {
    topAsn,
    topPayload,
    topIp: asnRow?.src_ip,
  };
}

export async function ensureSopsInVectorize(env: SocEnv): Promise<void> {
  const seeded = await env.ACTIVE_BLOCKS.get(META_SOPS_SEEDED);
  if (seeded === '1') return;

  const vectors: VectorizeVector[] = [];
  for (const sop of SECURITY_SOPS) {
    const text = `${sop.title}\n${sop.body}`;
    const emb = (await env.AI.run(EMBEDDING_MODEL as any, {
      text: [text],
    })) as { data?: number[][] };
    const values = emb.data?.[0];
    if (!values || values.length === 0) continue;
    vectors.push({
      id: sop.id,
      values,
      metadata: { title: sop.title, body: sop.body.slice(0, 2000) },
    });
  }

  if (vectors.length) {
    await env.VECTORIZE.upsert(vectors);
  }
  await env.ACTIVE_BLOCKS.put(META_SOPS_SEEDED, '1');
}

export async function retrieveSopContext(env: SocEnv, symptom: string): Promise<string> {
  await ensureSopsInVectorize(env);
  const emb = (await env.AI.run(EMBEDDING_MODEL as any, {
    text: [symptom],
  })) as { data?: number[][] };
  const vec = emb.data?.[0];
  if (!vec) return '';

  const matches = await env.VECTORIZE.query(vec, {
    topK: 3,
    returnMetadata: 'all',
  });
  const lines: string[] = [];
  for (const m of matches.matches ?? []) {
    const meta = m.metadata as { title?: string; body?: string } | undefined;
    if (meta?.title) {
      lines.push(`- ${meta.title}: ${meta.body ?? ''}`);
    }
  }
  return lines.join('\n');
}

export async function persistBlocksToKv(
  env: SocEnv,
  wafRule: Record<string, unknown>,
): Promise<void> {
  const target = wafRule.target as { asn?: number; ip?: string } | undefined;
  const ts = Date.now();
  const payload = JSON.stringify({ source: 'soc_agent', ts, wafRule: wafRule.kind });
  if (typeof target?.asn === 'number') {
    await env.ACTIVE_BLOCKS.put(`asn:${target.asn}`, payload, { expirationTtl: 60 * 60 * 24 * 30 });
  }
  if (typeof target?.ip === 'string' && target.ip.length > 0) {
    await env.ACTIVE_BLOCKS.put(`ip:${target.ip}`, payload, { expirationTtl: 60 * 60 * 24 * 30 });
  }
}

export type BroadcastPayload = Record<string, unknown>;

export async function notifyTicket(
  env: SocEnv,
  ticketId: string,
  payload: BroadcastPayload,
): Promise<void> {
  const id = env.INVESTIGATION_TICKET.idFromName(ticketId);
  const stub = env.INVESTIGATION_TICKET.get(id);
  await stub.fetch(
    new Request('https://internal/broadcast', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    }),
  );
}
